#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV
#export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity160_v1"
export PILEUPDISTFUNCHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/pileup_distfunc_pPb_2sigma_mode1.root"

export ISCORR=0

export PTTRGMINARRAY="0.1"
export PTTRGMAXARRAY="10000.0"
export PTASSMINARRAY="0.1"
export PTASSMAXARRAY="10000.0"

#export NVTXMAX=100000

NMIN=(-1)
NMAX=(-1)
