#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV
export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity130_v1"

export ISCORR=0

export PTTRGMINARRAY="0.1"
export PTTRGMAXARRAY="10000.0"
export PTASSMINARRAY="0.1"
export PTASSMAXARRAY="10000.0"

NMIN=(-1)
NMAX=(-1)
