 {  

    gStyle->SetPalette(1,0);
      gStyle->SetPadColor(0);
      gStyle->SetPadBorderSize(0);
      gStyle->SetPadBorderMode(0);
      gStyle->SetCanvasColor(0);
      gStyle->SetCanvasBorderMode(0);
      gStyle->SetCanvasBorderSize(0);
      gStyle->SetFrameBorderMode(0);
      gStyle->SetFrameLineColor(0);
      gStyle->SetTitleBorderSize(0);
      gStyle->SetPalette(1,0);
      gStyle->SetPadTickX(1);
      gStyle->SetPadTickY(1);
      gStyle->SetPadColor(0);
      gStyle->SetPadBorderSize(0);
      gStyle->SetPadBorderMode(0);
      gStyle->SetCanvasColor(0);
      gStyle->SetCanvasBorderMode(0);
      gStyle->SetCanvasBorderSize(0);
      gStyle->SetFrameBorderMode(0);
      gStyle->SetFrameLineColor(0);
      gStyle->SetFrameFillColor(0);
      gStyle->SetTextFont(43);
      gStyle->SetTextSize(41);
      gStyle->SetLabelFont(43,"XYZ");
      gStyle->SetTitleFont(43,"XYZ");
      gStyle->SetTitleColor(1);
      gStyle->SetTitleBorderSize(0);
      gStyle->SetTitleXSize(25);
      gStyle->SetTitleYSize(25);
      gStyle->SetTitleXOffset(1.);
      gStyle->SetTitleYOffset(1.22);
      gStyle->SetLabelSize(18,"XYZ");
      gStyle->SetLabelOffset(0.001,"X");
      gStyle->SetLabelOffset(0.001,"Y");

      gStyle->SetTitleColor(1,"XYZ");
      gStyle->SetHistLineColor(1);
      gStyle->SetHistLineStyle(0);
      gStyle->SetHistLineWidth(3);
      gStyle->SetHistLineWidth(1);
      gStyle->SetEndErrorSize(0);
      gStyle->SetErrorX(0);
      gStyle->SetMarkerStyle(20);
      gStyle->SetMarkerSize(1.25);
      gStyle->SetOptFit(1111);
      gStyle->SetStatColor(0);
      gStyle->SetStatBorderSize(1);
      gStyle->SetOptStat(0);
      gStyle->SetPadLeftMargin(0.19);
      gStyle->SetPadBottomMargin(0.16);
      gStyle->SetPadTopMargin(0.05);
      gStyle->SetPadRightMargin(0.08);
      // gStyle->SetPadRightMargin(0.15);
      
}
