#!/bin/sh

currentdir=$PWD

#dataset=HIData_Minbias_2760GeV_HighPtTrack2011_pixeltracks
#dataset=PAData_Minbias_5TeV_TRIGGER100_Express
#datadir=/mnt/hadoop/cms/store/user/davidlw/store/caf/user/davidlw/PA2013_FlowCorr_Express_v2
#datadir=/mnt/hadoop/cms/store/user/tuos/HIMinBiasUPC/FlowppTracking_Skim_HIRun2011_HIMinBiasUPC-peripheral/*
#datadir=/mnt/hadoop/cms/store/user/davidlw/HIHighPt/PR2011_HighPtTrack12_pixeltracks_TRKANASKIM_official_v6/*
#datadir=/mnt/hadoop/cms/store/user/davidlw/MinBias_TuneZ2star_7TeV_pythia6_442p5_v1/NMult170/Skims

dataset=PAData_Minbias_5TeV_HM_PromptReco
datadir=/mnt/hadoop/cms/store/user/davidlw/PAHighPt/PA2013_FlowCorr_PromptReco_v4/*

#dataset=PAData_Minbias_5TeV_HM_Express_run210676-210759
#datadir=/mnt/hadoop/cms/store/user/davidlw/store/caf/user/davidlw/PA2013_FlowCorr_Express_run210676-210759_v3

#dataset=PAData_Minbias_5TeV_HM_PromptSkim
#datadir=/mnt/hadoop/cms/store/user/davidlw/PAHighPt/PA2013_FlowCorr_PromptSkim_v3/*

#dataset=PPData_Minbias_7TeV_MINBIAS_2010B_Apr21ReReco
#dataset=PPData_Minbias_7TeV_TRIGGER85_2010B_Apr21ReReco
#dataset=PPData_Minbias_7TeV_TRIGGER70_2010B_Apr21ReReco
#dataset=PPData_Minbias_7TeV_TRIGGER100_2010B_Apr21ReReco
#dataset=PPData_Minbias_7TeV_MINBIAS_2010A_Apr21ReReco
#dataset=PPData_Minbias_7TeV_TRIGGER85_2010A_Apr21ReReco
#dataset=PPData_Minbias_7TeV_TRIGGER70_2010A_Apr21ReReco
#dataset=PPData_Minbias_7TeV_MINBIAS_C10_398p2

#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010A_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_minbias/*/*/*/*
#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010A_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_trigger70/*/*/*/*
#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010A_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_trigger85/*/*/*/*
#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010B_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_minbias/*/*/*/*
#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010B_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_trigger100/*/*/*/*
#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010B_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_trigger70/*/*/*/*
#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010B_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_trigger85/*/*/*/*

mkdir -p filesets
ls -l $datadir/*HM_*.root  | awk '{print "file:" $9}' > ./filesets/fileset_${dataset}.txt
